# site settings
title: 2258Studio
subtitle: by Manuel Schmidbauer
email: manuel2258@protonmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: https://2258studio.com

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# build settings
markdown: kramdown

sass:
  style: compressed
